application: worthy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /public
  static_dir: public

- url: .*
  script: main.app

skip_files:
- ^sass-cache(/.*)?
- .*sass-cache
- ^node_modules(/.*)?
- .*node_modules

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest